- name: Linux Health
  hosts: all
  gather_facts: yes


  tasks:
  - name: check disk usage
    command: df -h
    register: disk 
  - name: check memory usage 
    command: free -h 
    register: memory
  - name: check uptime 
    command: uptime 
    register: uptime

  - name: display disk usage
    debug:
      var: disk.stdout
  - name: display memory usage
    debug:
      var: memory.stdout
  - name: display uptime
    debug:
      var: uptime.stdout
