- name: Linux Health
  hosts: localhost
  gather_facts: yes


  tasks:
  - name: check disk usage
    command: df -h
    register: disk 
  - name: check uptime 
    command: uptime 
    register: uptime_info
  - name: display disk usage
    debug:
      var: disk.stdout
  - name: display 
    
